In [3]:
# Perbedaan penjumlahan pada numpay array dan list
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = [1, 2, 3, 4, 5]

print(a)
print(b)

a += 1
b += [1]

print(a)
print(b)

[1 2 3 4 5]
[1, 2, 3, 4, 5]
[2 3 4 5 6]
[1, 2, 3, 4, 5, 1]


In [6]:
# Membuat vector
a = np.array([1, 2, 3, 4, 5])
b = np.array([1.5, 2.2, 3.1, 4, 5.9])

# Membuat vector dengan range
c = np.arange(1, 10, 2)

# Membuat linspace
d = np.linspace(1, 13, 4)

print(a)
print(b)
print(c)
print(d)

[1 2 3 4 5]
[1.5 2.2 3.1 4.  5.9]
[1 3 5 7 9]
[ 1.  5.  9. 13.]


In [7]:
# Array multidimensi / matrix
a = np.array([(1, 2, 3), (-1, -1, 1), (0, -3, 5)])
print(a)

[[ 1  2  3]
 [-1 -1  1]
 [ 0 -3  5]]


In [8]:
# Matrix dengan nilai 0
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [9]:
a = np.zeros((5, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
# Matrix dengan nilai 1
a = np.ones(4)
b = np.ones((4, 4))
print(a)
print(b)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Membuat matrix identitas
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
